
CREATE TABLE AUTH_NAMES
(
  AUTH_NAME VARCHAR(100) NOT NULL COMMENT '접근권한명',
  UNIQUE_ID VARCHAR(100) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '접근권한명';

CREATE TABLE AUTHS
(
  UNIQUE_ID_USERS      VARCHAR(100) NOT NULL COMMENT '대표값',
  UNIQUE_ID_AUTH_NAMES VARCHAR(100) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
) COMMENT '권한들';

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '아이디',
  PW  VARCHAR(200) NOT NULL COMMENT '비밀번호',
  EMAIL     VARCHAR(200) NOT NULL COMMENT '이메일',
  NAME      VARCHAR(200) NOT NULL COMMENT '이름',
  GENDER_ID  VARCHAR(200) NOT NULL COMMENT '성별_ID',
  BIRTHDATE  VARCHAR(200) NOT NULL COMMENT '생년월일',
  TELECOM_ID VARCHAR(200) NOT NULL COMMENT '통신사_ID',
  PHONENUM   VARCHAR(200) NOT NULL COMMENT '휴대폰번호',
  POSITION  VARCHAR(200) NULL     COMMENT '직책',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자들';

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_USERS_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_USERS)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_AUTH_NAMES_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_AUTH_NAMES)
    REFERENCES AUTH_NAMES (UNIQUE_ID);